Practice 1
ArtyomLobanov/MLBD pull request #1
Opened 2020-02-05 11:42 UTC by ArtyomLobanov

2020-02-05 11:44 UTC, ArtyomLobanov commented
@ishugaepov, сделал пул-реквест в свой мастер

2020-02-06 17:04 UTC, ishugaepov requested changes

2020-02-06 17:04 UTC, ishugaepov commented on apache_spark/notebooks/spark_examples.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAABMoAAAS/CAYAAAD7HBRLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAWJQAAFiUBSVIk8AAAADl0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uIDMuMC4zLCBodHRwOi8vbWF0cGxvdGxpYi5vcmc
Задание "Распределение рейтингов фильмов":

Не используйте округление.
В `plt` есть метод `hist`, который позволит вам построить гистограмму без необходимости самому разбивать данные по бакетам

2020-02-06 17:04 UTC, ishugaepov commented on apache_spark/notebooks/spark_examples.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAABMoAAAS/CAYAAAD7HBRLAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAWJQAAFiUBSVIk8AAAADl0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uIDMuMC4zLCBodHRwOi8vbWF0cGxvdGxpYi5vcmc
Задание "Распределение числа оценок для фильмов": 
Тут тоже самое - не нужно самостоятельно разбивать данные на бакеты.
Воспользуйтесь методом `plt.hist`.

(Возможно задание было сформулировано не достаточно ясно, но речь шла о скорее о визуализации, а не о том чтобы `rdd` фактически превратить в гистограмму)

2020-02-11 23:14 UTC, ArtyomLobanov commented
@ishugaepov, Я переписал создание гистограмм в указанных заданиях через pyplot.hist

2020-02-15 20:36 UTC, merged